### ISSUE TITLE
mutations in macros to compile-time variable is not observable via another compile-time function

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#1022]
### Example

```nim
var x {.compileTime.} = 10
proc foo(): int {.compileTime.} = x

macro echoFoo(): untyped =
  inc x
  inc x
  inc x
  echo foo()
  echo x

echoFoo()
```

### Actual Output

```
10
13
```

### Expected Output

```
13
13
```

### Additional information

* Found while working on [disruptek/balls](https://github.com/disruptek/balls).

**Comment by zerbina** [comment]
The problem is that the `foo()` call is folded into `10` during semantic analysis of the macro body. There exists logic to prevent exactly this kind of issue, but it doesn't consider compile-time-only routines.

I'll make a PR with the fix.

**Comment by saem** [comment]
@alaviss this should be fixed, could you give it a quick shot to confirm?

**Comment by alaviss** [comment]
Yep, it's working.

I wonder what's wrong with Github today. It hasn't been auto closing issues.
