### ISSUE TITLE
error in nim.cfg does not make the compiler quit with an error code

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#1112]
### Example

Use this `test.nim.cfg` with an empty `test.nim`:

```text
--gibberish
```

### Actual Output

```
$ nim c test.nim || echo got error
test.nim.cfg(1, 3) Error: Invalid command line option - gibberish
```

### Expected Output

```
$ nim c test.nim || echo got error
test.nim.cfg(1, 3) Error: Invalid command line option - gibberish
got error
```

### Possible Solution

* Write error handling code for this case: https://github.com/nim-works/nimskull/blob/7e7226f1904360c2e14c8f57fc9e0f61e5483d58/compiler/nim.nim#L159-L161

**Comment by zerbina** [comment]
Resolved by #1119, but was not closed automatically.
