### ISSUE TITLE
discardable ignored in try/finally block

### ISSUE THREAD

**Issue by disruptek** [nim-works/nimskull#1178]
### Specification

The `discardable` pragma is ignored in `try` statements when the `except` clause is missing and a `finally` clause terminates the statement.

### Example

```nim
proc foo(): int {.discardable.} =
  42

try:
  foo()
finally:
  discard
```

### Actual Output
```
Error: expression 'foo()' is of type 'int' and has to be used (or discarded)
```
### Expected Output
```
```
### Additional Information

I've encountered errors with `discardable` which may have been in other contexts, so when debugging this I'd probably start with looking at the pragma and then move on to looking at `try`, though I think `try` was modified recently, so...  :shrug:

```
Nimskull Compiler Version 0.1.0-dev.21220 [linux: amd64]

Source hash: c604a5d6cb1548bff241bf7ccc8b5181182effbd
Source date: 2024-02-11
```

**Comment by saem** [comment]
I can take a look at this.

**Comment by saem** [comment]
Fixed in https://github.com/nim-works/nimskull/pull/1185, wasn't auto-closed.
