### ISSUE TITLE
Use C++ 17

### ISSUE THREAD

**Issue by ringabout** [nim-works/nimskull#12]
Merge https://github.com/nim-lang/Nim/pull/17375

> Initialization of parent struct in C++ appeared only in C++17.

It solves many issues. As a bonus the compiler itself can be bootstrapped by `--gc:orc -b:cpp`.
fix https://github.com/nim-lang/Nim/issues/18410
fix https://github.com/nim-lang/Nim/issues/17351
A workaround can be removed: https://github.com/nim-lang/Nim/pull/18836#issuecomment-927052590

**Comment by alaviss** [comment]
C++ backend is on the flaky side. We don't even know what are its expectations and what is the generator design.

I'd say changes to it will be on very low priority.

**Comment by disruptek** [comment]
I see two issues enumerated and it's impossible to know how many issues will be introduced.  I think we have to ignore the backends until they are the weak link; garbage in, garbage out, right.

Though I admit that I do wish the cpp backend worked more often, and I'm curious if this could help CPS's C++ codegen issues. :grimacing:

**Comment by saem** [comment]
> I see two issues enumerated and it's impossible to know how many issues will be introduced. I think we have to ignore the backends until they are the weak link; garbage in, garbage out, right.

I totally agree that this is very low priority and I've got no interest in supporting knock on effects. Guess that means that the near term mission needs further clarification.

**Comment by saem** [comment]
@xflywind can you reread the readme to see what's the mission right now and based on your understanding do one of the following:
- start a discussion asking to expand the scope and how you'll support that expansion
- open an issue, asking to clarify the near term mission, along with your current interpretation

I'd like to avoid doing this issue by issue stuff, as that's painful for everyone, and at the same time want to make sure you're heard and vice versa.

**Comment by ringabout** [comment]
Fair enough. The alternative way is https://github.com/nim-lang/Nim/pull/18836 to workaround one of the issues.
