### ISSUE TITLE
CI failures due to inconsistent binaries buildt on M1 runners 

### ISSUE THREAD

**Issue by Clyybber** [nim-works/nimskull#1231]
Sometimes the [Binaries from git and source archive should be the same](https://github.com/nim-works/nimskull/blob/devel/.github/workflows/ci.yml#L554) check fails, presumably because of SDK updates making it to one runner before the other.

Most of the times it's [Build release artifacts from source archive (macOS (M1))](https://github.com/nim-works/nimskull/blob/devel/.github/workflows/ci.yml#L322) that needs to be restarted to fix the failure,
other times it's [Build release binaries (macOS (M1))](https://github.com/nim-works/nimskull/blob/devel/.github/workflows/ci.yml#L122) that needs restarting.

The most recent example at the time of writing can be seen at https://github.com/nim-works/nimskull/actions/runs/8237550847/job/22531163678#step:9:30

**Comment by zerbina** [comment]
Addressed by #1244. There haven't been any MacOS SDK version-related issues since.
