### ISSUE TITLE
incorrect control-flow when indirect call raises with `--panics:on`

### ISSUE THREAD

**Issue by saem** [nim-works/nimskull#1253]
### Specification

Indirect calls with procedural values that don't have an explicit exception specification are treated as not raising an exception, when `--panics:on`, resulting in improper control-flow.

### Example

```nim
# build with `--panics:on`

type Proc = proc () {.nimcall.}

proc test(x: Proc) =
  try:
    x()
  except CatchableError:
    echo "caught"

test(proc() =
  raise CatchableError.newException("")
)
```

### Actual Output

```
Error: unhandled exception:  [CatchableError]
```

### Expected Output

```
caught
```

### Additional Information

* reduced from this [insideout branch's test](https://github.com/disruptek/insideout/blob/c324ceaaa78d6de6eca4c9d92bf59947010dd83e/tests/t33_links.nim)
* with the following [workaround](https://github.com/disruptek/insideout/blob/c324ceaaa78d6de6eca4c9d92bf59947010dd83e/insideout/runtimes.nim#L370), the aforementioned insideout test succeeded

**Comment by saem** [comment]
Once we learn a bit more edit this issue so it's a bit easier to understand/search for later.

**Comment by saem** [comment]
From disruptek

> I looked at the codegen earlier and it feels like a mir bug wherein a goto is missing in the simple case.  you still need to have a call in there though.

**Comment by zerbina** [comment]
I've reduced the bug, updated the issue accordingly, and am now working on a fix.

**Comment by saem** [comment]
@disruptek can you confirm the latest nimskull fixes this for you?

**Comment by disruptek** [comment]
74 works, thanks.
