### ISSUE TITLE
overflow checks cannot be disabled for integer negation in the VM

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#1406]
### Example

```nim
{.push checks:off.}
proc `-%`(a: uint64): uint64 =
  ## Perform 2-complement negation on `a`
  result = cast[uint64](-cast[int64](a))
{.pop.}

discard -%(cast[uint64](low(int64)))
```

### Actual Output

```
$ nim r --backend:vm test.nim
stack trace: (most recent call last)
test.nim(1, 2) NimMain
test.nim(7, 9) test
test.nim(4, 25) -%
test.nim(4, 25) Error: over- or underflow
```

### Additional Information

- Works fine for C and JS backends

**Comment by zerbina** [comment]
Overflow checks in general aren't affected, just negation. This is because the code generator always emits `opcUnaryMinusInt` and (which checks for overflows), even if the operation is unchecked.

**Comment by saem** [comment]
Fixed in https://github.com/nim-works/nimskull/pull/1408
