### ISSUE TITLE
Variables in `{.compileTime.}` cannot be captured if the capturing closure is nested twice

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#1425]
### Example

```nim
proc foo() {.compileTime.} =
  var x = 0

  proc bar() =
    proc foobar() =
      x = 1

    foobar()

  bar()

static: foo()
```

### Actual Output

```
test.nim(6, 7) Error: 'x' is inaccesible because run-time values cannot be captured in a compile-time context
```

### Additional Information

* If `foobar` body is inlined into `bar`, no error will occur.

* This is found while fixing `npeg`.

**Comment by zerbina** [comment]
The example code not working is deliberate, although for no good nor principled reason -- I'll remove the arbitrary restriction.
