### ISSUE TITLE
Self-referencing distinct will cause the compiler to hang

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#148]
### Example

```nim
type Id = distinct Id
```

### Actual Output
The compiler stuck at 100% CPU usage

### Expected Output
Some errors about self-referencing

**Comment by metagn** [comment]
https://github.com/nim-lang/Nim/issues/5282

https://github.com/nim-lang/Nim/issues?q=is%3Aissue+is%3Aopen+type+recursion

**Comment by alaviss** [comment]
Here are talks about a potential fix in chat:

https://matrix.to/#/!MAXxvfCYnfYgZqSizw:matrix.org/$sTAkRoPD9ZPca05Uh_JtoONN-z-J3ZVl7j_VNRWyGPM?via=libera.chat&via=matrix.org&via=envs.net

**Comment by zerbina** [comment]
The linked PR fixed the bug -- an `illegal recursion in type 'Id'` error is now reported.
