### ISSUE TITLE
structure gc memory statistics data

### ISSUE THREAD

**Issue by haxscramper** [nim-works/nimskull#192]
The GC memory statistics data is generated in the `gc.nim` and then printed when the compiler is executed. This is a compiler report, it must also be structured and have the data accessible.

```nim
  proc GC_getStatistics(): string =
    result = "[GC] total memory: " & $(getTotalMem()) & "\n" &
             "[GC] occupied memory: " & $(getOccupiedMem()) & "\n" &
             "[GC] stack scans: " & $gch.stat.stackScans & "\n" &
```

Right now the data is not structured, and it is printed in the

```nim
  when declared(GC_setMaxPause):
    echo GC_getStatistics()
```

in the `nim.nim`

- [ ] refactor the `GC_getStatistics` into "get data" (add `NimGcStats` or similarly-named objet (to avoid clashes) and make `GC_getStatisticsData()` procedure that returns this) and "format data" stages. Old `GC_getStatistics` can be implemented as `getGcData().formatGcData()`
- [ ] Store the GC report in the `reports.InternalReport` field. Add `rintGcStatistics` report kind and put this field under the branch in report definition.
- [ ] Format report just like any other in the `cli_reporter.reportBody` for the `InternalReport`

**Comment by canelhasmateus** [comment]
on the case

**Comment by saem** [comment]
This is no longer valid
