### ISSUE TITLE
add `debugAst()`, `debugType()` and `debugSym()` procs back to `astrepr`

### ISSUE THREAD

**Issue by haxscramper** [nim-works/nimskull#203]
- [x] Add overload of the `treeRepr` that does not accept `ConfigRef` object
- [x] Allow passing nil `conf` to the `treeRepr`
- [x] Add helper procedures - `debugAst()`, `debugType()` and `debugSym()` with `{.exportc.}` annotations to be used in the debugging

https://github.com/nim-works/nimskull/pull/191 removed API a little too aggressively - the no-argument debug still needs to be present

**Comment by krux02** [comment]
I didn't see that you took out `debug` entirely in the old PR. Github in being github was smart and decided that the files with the most changes are not important enough to be shown.
