### ISSUE TITLE
Matrix inaccessable

### ISSUE THREAD

**Issue by ShalokShalom** [nim-works/nimskull#250]
After already posting it around a week ago in IRC:

The Matrix channel is dubious to me:
It shows up on the bottom, other than as a dedicated channel.

And then, when I tap it, I get to an interface, which seems unrelated.

![Screenshot_20220312-221621~2](https://user-images.githubusercontent.com/6344099/158035296-1adfacab-2986-47a1-aacf-53e370b7a578.png)
![Screenshot_20220312-221612](https://user-images.githubusercontent.com/6344099/158035298-cd6bea16-5233-453f-b58a-3f423f95f41f.png)

**Comment by alaviss** [comment]
Hi, this seems to be a problem with FluffyChat where the client does not fully support Matrix Spaces. You should be able to discover and join the rooms using a supporting client like Element (you can do that on the web).

Once you have joined the rooms they should show up on FluffyChat.

**Comment by ShalokShalom** [comment]
When I click your Matrix link on the Readme, it literally takes me to a page, that lets me download and recommends Fluffy as well. Did you miss to test this?

**Comment by alaviss** [comment]
> Did you miss to test this?

Pretty much, I use Element on my desktop so matrix.to always default to it.

With #251, the link should now show only Element and hides other clients under a button. This should prevent new users from picking an option that may not support Spaces well and face issue similar to yours.

Please let us know if you manage to join using Element.
