### ISSUE TITLE
RST syntax errors in docgen are not reported properly

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#264]
### Example
```nim
proc foo*() =
  ## `x
  discard
```

### Actual Output
```
$ bin/nim doc test.nim
........................................................
'`' expected
lineinfos.nim(190)       raiseRecoverableError
Error: unhandled exception: report [ERecoverableError]
```

### Expected Output
```
test.nim(2, 6) Error: '`' expected
```

### Additional Information

* This doesn't seem to be an issue for upstream

### References

This caused confusion in #261 where we have no idea why docgen failed.

**Comment by saem** [comment]
Fixed as part of #505.

Specifically, the change in `cli_reporter`'s `reportFull` proc for `BackendReport` wasn't outputing the full message. Now it provides line info and all that jazz.
