### ISSUE TITLE
Exclude `reKnownIssue` from the "print failed tests" stage in CI

### ISSUE THREAD

**Issue by haxscramper** [nim-works/nimskull#456]
While this might be helpful in some cases that I'm not aware of, it makes quick browsing for failures more confusing than necessary. In my understanding "print failed tests" is inteded to make the quick skimming easier, so I suggest hiding "known issue" failures from the failed test.

**Comment by haxscramper** [comment]
Ping @alaviss and @saem -- is this an acceptable change or you prefer to keep the known issue visible by default.

**Comment by saem** [comment]
I think reporting them in their own category is the way to go. We need to know if one suddenly starts passing.

It really should be more clear.

**Comment by alaviss** [comment]
We should have a different tool for tracking known issues, so I think `ci_testresults` should not bother with them for now.
