### ISSUE TITLE
Streamline development and build processes for CI and users

### ISSUE THREAD

**Issue by alaviss** [nim-works/nimskull#89]
There are a few issues with the compiler development/build processes:

- Requires `PATH` modification to run all tests.
- Requires a bootstrap compiler, but further build invocations will replace it, hiding bootstrap bugs until they hit CI. This might also frustrate developers who start from an old tree cluttered with build artifacts.
- It is a PITA to build the bootstrap compiler.
- Build artifacts are littered all over the tree.

This issue tracks the efforts in reducing friction and increasing build reliability.

- [x] #85 
- [x] Remove bootstrapping (implicit) dependency on users configuration
- [x] Remove main test suite dependency on `nim` in `PATH`
- [ ] #126
- [x] Easy generation of a compiler source archive
- [x] Easy generation of a release compiler binary archive

**Comment by alaviss** [comment]
Per discussion with @haxscramper, we might want to disable the use of user configuration altogether in compiler bootstrap.

Is this desirable and should we take a step further and disable it for the compiler source tree altogether?

@saem @disruptek

**Comment by saem** [comment]
Very much agree.

I think configuration during bootstrap can't be a free for all. We should ratchet it down to zero as a start.

The sinking feeling I have is that were going to need some version over time crap one fine day, because mistakes will have been made. So the lock down now reduces that chance, or at least reduces the complexity.

**Comment by alaviss** [comment]
With the recently merged PRs this is pretty much done.

Consolidating build artifacts will be a rather complicated endeavor, given that a lot of our tools rely on being exactly where they are in the source tree. Work on this portion will need a lot of discussion, so it should be left for later.
