### ISSUE TITLE
specification to merge documentation with code

### ISSUE THREAD

**Issue by krux02** [nim-works/nimskull#9]
Not fully formal yet, but these were my comments on IRC

I think documentation is attached to nodes, and it would be nice is this documentation to node attachment would be specified clearly and is extended generally.
for example documentation for functions contain documentation for function arguments.
this means a doc comment doesn.t just document one fucntion, it does document a whole tree of nodes
therefore it is good to specifiy a grammer how subnodes can be documented in a doc comment
so that you can attach documentation to everything from everywhere
and at the end the parser merges all these possible sources of documentation is a specified order to have the full documentation.
this means you can put function documentation including arguments documentation at the top level module documentation, or in the seperate documention file
runnable examples could just be normal example code in the mymodule.doc file

**Comment by saem** [comment]
Let's move this to a discussion or gist, I'd like to keep issues actionable.
